### ISSUE TITLE
vue-f7-tabs' is not in the npm registry

### ISSUE THREAD

**Issue by dgk4201** [phonegap/phonegap-template-vue-f7-tabs#4]
npm ERR! 404 Registry returned 404 for GET on https://registry.npmjs.org/vue-f7-tabs
npm ERR! 404
npm ERR! 404  'vue-f7-tabs' is not in the npm registry.

**Comment by devgeeks** [comment]
Ah yes... this is a README fail. There is no alias in the PhoneGap CLI yet for these templates (and it might end up being `tabs-vue` instead anyway.

Just use `phonegap create MyAppName --template phonegap-template-vue-f7-tabs` instead for now.

And just a helpful tip, doing a `phonegap template list` will give you the list of aliased templates available to the PhoneGap CLI...

**Comment by devgeeks** [comment]
I'll fix the README
